### ISSUE TITLE
add scoring for papers with putative MHC-restriction

### ISSUE THREAD

**Issue by iziziz** [antigenomics/vdjdb-db#108]
add rule for scoring of CDR from papers where not possible to determine MHC-restriction for antigen explicitly.
It's only about such papers:
- antigen-loaded-target or antigen-expressing-target isolation/verification
- detection of clones on the basis of IFNg or TNF release
- antigen-presenting cells should be positive for putative MHC-allele presenting the antigen
- antigen peptide should be from "commonly used" pool: like NLV peptide

E.g. clonotypes reactive against A*02-positive cells loaded by NLV peptide

Suggestion:
add phrase "putative MHC-restriction" to method.isolation for such seqs
add putative MHC allele to mhc.a/mhc.b column(s)

**Comment by mikessh** [comment]
We also need to list such papers here
