### ISSUE TITLE
PMID:25911754

### ISSUE THREAD

**Issue by ewaldvandyk** [antigenomics/vdjdb-db#122]
http://www.ncbi.nlm.nih.gov/pubmed/?term=25911754

**Comment by ewaldvandyk** [comment]
I want to upload some data from a paper. But the instructions on how to do this is not clear at all.

For example, I have no clue how to label my issue as "paper" (can't find any way of editing this). 
Also I have no clue what "Don't forget to close/reference corresponding issues in the commit message" means.

Please provide a step by step visual guide with a clear example.

Best,
Ewald

**Comment by mikessh** [comment]
Hello @ewaldvandyk 
Making a visual guide is a good idea (your questions are mostly related to github interface). You can label you issue as a paper by clicking Labels at the right side of this page. To close the issue you need to add "Close #122" (issue number) to your commit message. Also, it is recommended to create a separate branch named #122 and mark all commits with "#122" tag.
You can try the following steps: fork the repository, add your submission chunk to ``chunks/`` folder, commit it and create a pull request with the issue id in the pull request message.
You can also wait until I'll generate an additional readme with step by step instructions.

**Comment by ewaldvandyk** [comment]
Thanks for the fast response. 
I still cannot figure out how to label the issue. I looked everywhere. The only thing I can see on the right is "Labels: Not yet" but there seems to be no way to edit it. Maybe a browser issue (I'm using safari) or I don't have permission?

**Comment by mikessh** [comment]
Sorry, my bad, I thought you were added to this repository (added you as collaborator). This label is mostly for internal/admin purposes and to tell published data from unpublished (``communication`` label)

**Comment by ewaldvandyk** [comment]
Cool thanks!
