### ISSUE TITLE
V/J mapping-2

### ISSUE THREAD

**Issue by mikessh** [antigenomics/vdjdb-db#175]
* Check old/new segments
* Ensure original (authors') V segment is not changed if 1) it is found in the segment DB, 2) it has a match of at least ``2`` AA, 3) It has a match of more than ``3`` AAs or alternative match is only ``1`` or ``2`` AA longer
> NB: Numbers subject to discussion

**Comment by vadimnazarov** [comment]
Currently I replace segments only if there is "null" or the new segments has three or more aligned amino acids. It's quite strict however in this case we are sure that this is not a coincidence. I will show statistics of replacements off-line.

There is another problem - there are quite many segments with identical alignments. Again I will show statistics later and won't close this issue yet.

**Comment by mikessh** [comment]
There is some mess in cdr3fixer json + sometimes sequences with good alignment are marked as unaligned (e.g. CAAMEGAQKLVF and other sequences from complexes)

Comes from https://github.com/antigenomics/vdjdb-server/issues/21
