### ISSUE TITLE
Frequency proofreading

### ISSUE THREAD

**Issue by RenskeVroomans** [antigenomics/vdjdb-db#213]
A student noticed an error in the frequency notation of one entry: it was written 1//50 rather than 1/50. I fixed the entry, but I wondered if there is any proofreading on the frequency format?

**Comment by mikessh** [comment]
Hi!

Thats not a problem for VDJdb assembly scripts, the frequency is extracted as follows
```groovy
def x = freq.split("/+").collect { it.toFloat() }
```
meaning one or more dashes allowed. I actually think it is a feature - if you write ``1//10`` in excel it will not be converted to some other format.

**Comment by RenskeVroomans** [comment]
But then the frequency is converted to a float by the assembly script?
Because the database does still depict them as 3/100 etc.; so she found it because her own scripts analysing the data failed on the //. But if it is an allowed input I'll just tell her to adjust her own scripts accordingly.

**Comment by mikessh** [comment]
The frequency is both converted to float and inspected as a ratio (we have some scoring for both the % and the number of clones reported). I don't think I'm going to remove this feature, so I suggest modifying the script to have ``"//" -> "/"`` conversion.
