### ISSUE TITLE
Complex ID not exported

### ISSUE THREAD

**Issue by janwilamowski** [antigenomics/vdjdb-db#244]
When using the web interface, paired records are visible through the "Gene" column in the result table. However, when I export the data to a text file, this column is missing so I have no way of finding paired entries. Could you add this field to the export or provide an alternative way of accessing the information?

**Comment by mikessh** [comment]
Hello!

This issue is related to vdjdb web server and not the database itself, so I've transferred it here: https://github.com/antigenomics/vdjdb-web/issues/31 and closing this thread.

P.S. My bad, I need to update readme/about section of the vdjdb.cdr3.net to point to the vdjdb-web issue tracker
