### ISSUE TITLE
website down ?

### ISSUE THREAD

**Issue by kforner** [antigenomics/vdjdb-db#246]
Hi,
https://vdjdb.cdr3.net/ does not seem to work, is this expected ?
Thanks.

**Comment by mikessh** [comment]
Hello, works for me. Also http://downforeveryoneorjustme.com says its up. Please try again

PS I think all similar issues should go to https://github.com/antigenomics/vdjdb-web/issues. @bvdmitri can you please update all issue references on the web page to direct there

**Comment by kforner** [comment]
works now.
