### ISSUE TITLE
Unpaired sequences output when paired only box checked

### ISSUE THREAD

**Issue by dmstandley** [antigenomics/vdjdb-db#251]
Hi. In the VDJdb browser I selected "human" for species, checked TRA, TRB and "Only Paired records" in CDR3 tab, "MHCII" in MHC tab, then hit refresh button.  79 TRB records were output but only 10 TRA records. IS this expected? I thought by selecting "Only Paired records", the number of TRA & TRB would be equal.

However, when I downloaded the results to a text file, the situation was different:  The number of TRA & TRB records was equal (80), but the J gene was missing from all but 10 of the TRA entries. 

I didn't notice this pattern (lack of J gene names) for class I. Is this expected?

**Comment by mikessh** [comment]
Hello, I've moved this issue to the VDJdb browser repository https://github.com/antigenomics/vdjdb-web/issues/51. This repository issue section is for database content/curation/etc issues only.
