### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by amoudra** [antigenomics/vdjdb-db#264]
[Drobek A, Moudra A, Mueller D, Huranova M, Horkova V, Pribikova M, Ivanek R, Oberle S, Zehn D, McCoy KD, Draber P, Stepanek O. Strong homeostatic TCR signals induce formation of self-tolerant virtual memory CD8 T cells. EMBO J. 2018 May 11. pii: e98518. doi: 10.15252/embj.201798518](https://www.ncbi.nlm.nih.gov/pubmed/29752423)

**Comment by mikessh** [comment]
Everything seems fine now, thank you for submission!

**Comment by amoudra** [comment]
Thank you very much for your help!
