### ISSUE TITLE
Cannot access documentation to upload file to annotation

### ISSUE THREAD

**Issue by dannykwells** [antigenomics/vdjdb-db#266]
As instructed, I have tried to figure out the format to upload a list of TCR to the VDJDB for annotation (here: https://vdjdb.cdr3.net/annotations/info) but when I try to go to the link : http://vdjtools-doc.readthedocs.io/en/latest/ I get a message "You do not have sufficient permissions to view this page" 

I would very much like to use this tool and knowing the proper input format would help!

**Comment by mikessh** [comment]
Sorry, completely missed that. The correct link is http://vdjtools-doc.readthedocs.io/en/master/
