### ISSUE TITLE
V gene calls for TRA: CAVYYGQNFVF & TRB: CASSFQGYTEAFF

### ISSUE THREAD

**Issue by mjspindler** [antigenomics/vdjdb-db#284]
The TRA & TRB V-gene calls are not correct for the following CDR3 sequences. 
TRA: CAVYYGQNFVF & TRB: CASSFQGYTEAFF

In PMID: 16237109, the authors used an alternative nomenclature (from Arden B. et al., 1995; PMID: 8550092), not the IMGT nomenclature.

Comparing the Arden sequences with IMGT, I found TRAV16S1 (Arden) = TRAV3 (IMGT); TRBV3S1 (Arden) = TRBV28 (IMGT).

Is there a location that this type of nomenclature inconsistancies are documented?

Thank you.

For your reference:
TRAV16S1 nt: GAGTGGGCTGAGAGCTCAGTCAGTGGCTCAGCCGGAAGATCAGGTCAACGTTGCTGAAGGGAATCCTCTGACTGTGAAATGCACCTATTCAGTCTCTGGAAACCCTTATCTTTTTTGGTATGTTCAATACCCCAACCGAGGCCTCCAGTTCCTTCTGAAATACATCACAGGGGATAACCTGGTTAAAGGCAGCTATGGCTTTGAAGCTGAATTTAACAAGAGCCAAACCTCCTTCCACCTGAAGAAACCATCTGCCCTTGTGAGCGACTCCGCTTTGTACTTCTGTGCTGTGAGA

TRBV3S1 nt: ATGGGAATCAGGCTCCTCTGTCGTGTGGCCTTTTGTTTCCTGGCTGTAGGCCTCGTAGATGTGAAAGTAACCCAGAGCTCGAGATATCTAGTCAAAAGGACGGGAGAGAAAGTTTTTCTGGAATGTGTCCAGGATATGGACCATGAAAATATGTTCTGGTATCGACAAGACCCAGGTCTGGGGCTACGGCTGATCTATTTCTCATATGATGTTAAAATGAAAGAAAAAGGAGATATTCCTGAGGGGTACAGTGTCTCTAGAGAGAAGAAGGAGCGCTTCTCCCTGATTCTGGAGTCCGCCAGCACCAACCAGACATCTATGTACCTCTGTGCCAGCAGTTTATG

**Comment by mikessh** [comment]
Hello! Thanks for the information, we are currently working on this, see https://github.com/antigenomics/vdjdb-db/issues/221 and related issues
