### ISSUE TITLE
Clonal stability during MCMV memory inflation

### ISSUE THREAD

**Issue by VVenturi1** [antigenomics/vdjdb-db#309]
Manuscript accepted at The Journal of Immunology.
Title: Stochastic expansions maintain the clonal stability of CD8+ T cell populations undergoing memory inflation driven by MCMV
Authors: CJ Smith, V Venturi, MF Quigley, H Turula, E Gostick, K Ladell, BJ Hill, D Himelfarb, KM Quinn, HY Greenaway, THY Dang, RA Seder, DC Douek, AB Hill, MP Davenport, DA Price, CM Snyder 

[vdjdb_submission_MCMV_final.xlsx](https://github.com/antigenomics/vdjdb-db/files/3787019/vdjdb_submission_MCMV_final.xlsx)

**Comment by mikessh** [comment]
@VVenturi1 Dear Vanessa,
Thank you very much for the submission! All checks went smoothly.
Please let me know once the paper is published and indexed - right now the ``reference`` field points to this github page (https://github.com/antigenomics/vdjdb-db/issues/309) - I'll redirect it to PubMed once PMID is available.
