### ISSUE TITLE
PMID:28636589

### ISSUE THREAD

**Issue by huang7** [antigenomics/vdjdb-db#311]
M. tuberculosis specific TCRs from two papers:
1. PMID:28636589
Glanville J, Huang H, Nau A, Hatton O, Wagar LE, Rubelt F, Ji X, Han A, Krams 
SM, Pettus C, Haas N, Arlehamn CSL, Sette A, Boyd SD, Scriba TJ, Martinez OM,
Davis MM. Identifying specificity groups in the T cell receptor repertoire.
Nature. 2017 Jul 6;547(7661):94-98.

2. Provisional acceptance by NBT
Analyzing the CD4+ T cell response repertoire to M. tuberculosis and a platform for whole genome antigen discovery
Huang Huang, Chunlin Wang, Florian Rubelt, Thomas J. Scriba and Mark M. Davis

[Huang_VDJDBdatabase.xlsx](https://github.com/antigenomics/vdjdb-db/files/4037776/Huang_VDJDBdatabase.xlsx)

**Comment by mikessh** [comment]
Dear Huang,

Thanks a lot for the submission! I've added it to the database, all format checks seem to went fine. I'll add pubmed ID once you'll get one for your NBT paper.
