### ISSUE TITLE
PMID:31956412

### ISSUE THREAD

**Issue by drlcook** [antigenomics/vdjdb-db#312]
Hi,

I have populated the xlx spreadsheet template with antigen-specific TCR repertoire data for responses towards a deamidated gluten epitope in celiac patients and a CMV pp65 epitope in healthy individuals. The CMV-specific populations samples were either CD39+ (Treg) or CD39neg(Tconv) populations and have been separated into different spreadsheets.
[celiac_day6_CD39posTreg.xlsx](https://github.com/antigenomics/vdjdb-db/files/4141470/celiac_day6_CD39posTreg.xlsx)
[healthy_cmv_CD39negTconv.xlsx](https://github.com/antigenomics/vdjdb-db/files/4141471/healthy_cmv_CD39negTconv.xlsx)
[healthy_cmv_CD39posTregs.xlsx](https://github.com/antigenomics/vdjdb-db/files/4141472/healthy_cmv_CD39posTregs.xlsx)

**Comment by mikessh** [comment]
Added all data with minor fixes. Feel free to provide Pubmed IDs for CMV-specific sequences once they are published.

**Comment by drlcook** [comment]
Hi,

Thanks, please use the same PubMedID 31956412. CMV data was in the same publication.

On 10 Feb 2020, at 03:04, Mikhail Shugay <notifications@github.com<mailto:notifications@github.com>> wrote:


Added all data with minor fixes. Feel free to provide Pubmed IDs for CMV-specific sequences once they are published.

-
