### ISSUE TITLE
TCR-BST2 original article

### ISSUE THREAD

**Issue by fengxiaZhou** [antigenomics/vdjdb-db#314]
hi, could I know the title of  article that reported about the TCR-BST2 gene in the vdj database? when I click reference I was directed to the github page (https://github.com/antigenomics/vdjdb-db/issues/193) , but I would like to read the original article. Thank you!

**Comment by mikessh** [comment]
Hello, this is one of unpublished datasets communicated by Prof Andrew Sewell and colleagues, you can just cite VDJdb 2017 Nucleic Acids Research paper

**Comment by fengxiaZhou** [comment]
Thank you very much for your patient answers to my questions, the information you provided is very important to me.
Best regards
















At 2020-04-30 02:02:28, "Mikhail Shugay" <notifications@github.com> wrote:

Hello, this is one of unpublished datasets communicated by Prof Andrew Sewell and colleagues, you can just cite VDJdb 2017 Nucleic Acids Research paper
