### ISSUE TITLE
License of dataset

### ISSUE THREAD

**Issue by jannisborn** [antigenomics/vdjdb-db#322]
Under which license is the data of VDJdb distributed? I understand the code in this repo is CC-ND 4.0 licensed, but there is no note online on https://vdjdb.cdr3.net/about

A timely clarification would be appreciated. Thanks

**Comment by mikessh** [comment]
Hello,

This repository is actually the main storage of VDJdb content, so the content of the database to this date is currently issued under the "Creative Commons Attribution-NoDerivatives 4.0 International Public License" license. So one can use the database in their analysis if correct attribution is performed and one cannot make a copy (derivative) of the database for their own resource.

There is no specific license for code that is used to assemble the database (as there is not much sense, for it just supports VDJdb infrastructure and facilitates database builds), but I can issue it under Apache license if needed.

**Comment by jannisborn** [comment]
Many thanks for the fast reply and the maintenance of this great database. This helped a lot!
