### ISSUE TITLE
Any way/plans to include information about a *lack* of antigen association?

### ISSUE THREAD

**Issue by JamieHeather** [antigenomics/vdjdb-db#334]
I'm curious about whether there is/should be a way for people to report the lack of a specific TCR-pMHC interaction. 

Obviously sometimes this will occur within the bounds of a single paper that's discovered or is testing a particular TCR. However I certainly know of our and other groups who have reproduced published TCRs which don't replicate the stated specificity (which I presume is under-reported in the literature), yet which may remain as seemingly high confidence candidates in VDJdb.

Some kind of reporting system for negative associations might be instructive for people that use VDJdb to model interactions.

**Comment by mikessh** [comment]
In theory this can be included using "affinity" field in the database, e.g. ``no binding``, ``binding``, ``binding-low``, ``binding-high``, etc.

On practice there is too few data and we currently lack people to implement it. So we just keep/look for references to papers describing mutated ligands/TCRs, affinity assays, etc each time we want to build such control
