### ISSUE TITLE
PMID:35525797

### ISSUE THREAD

**Issue by FernandaLammoglia** [antigenomics/vdjdb-db#341]
[Lammoglia et al. Rapid single-cell identification of Epstein-Barr virus-specific T-cell receptors for cellular therapy. Cytotherapy 2022](https://pubmed.ncbi.nlm.nih.gov/35525797/)

Files supplied by the author:
[PMID_35525797_DB.xlsx](https://github.com/antigenomics/vdjdb-db/files/8651986/PMID_35525797_DB.xlsx)

**Comment by mikessh** [comment]
Thank you for this submission. I've added the paper label (only repository admins can do that) and edited your comment to add a link to the paper. We'll make a new release and publish the data to vdjdb web resource soon.
