### ISSUE TITLE
Nguyen et al., Cell Reports Medicine

### ISSUE THREAD

**Issue by hayleymc** [antigenomics/vdjdb-db#344]
Nguyen et. al., Robust SARS-CoV-2 T cell responses with common TCRαβ motifs towards COVID-19 vaccines in adult haematological malignancy patients with diseases and treatments impacting B cell immunity. Cell Reports Medicine. (pre-accepted)
Kedzierska Laboratory, Department of Microbiology and Immunology, The University of Melbourne
at the Peter Doherty Institute for Infection and Immunity
[cancer_tcrs_for_VDJdb.xls](https://github.com/antigenomics/vdjdb-db/files/10917162/cancer_tcrs_for_VDJdb.xls)

Thank you!

**Comment by mikessh** [comment]
Any updated on whether it is published?

**Comment by mikessh** [comment]
@hayleymc Is it this one? DOI:10.1016/j.xcrm.2023.101017? If yes, I'll add it asap
