### ISSUE TITLE
How to analyze the color on the cdr3 sequence

### ISSUE THREAD

**Issue by WindCanDie** [antigenomics/vdjdb-db#349]
Hello, I want to ask how the color of CDR3 is analyzed

`CASS`LAG`STEAFF`
green in front blue in back

**Comment by mikessh** [comment]
Green is the V germline part, blue is the J germline part - those are parts of Variable and Joining segment that are connected during V(D)J rearrangement, the central part contains Diversity segment that is not shown as it is often quite short and hard to identify and randomly added N-bases that are coding for random amino acids to increase the diversity.
