### ISSUE TITLE
PMID:38439958

### ISSUE THREAD

**Issue by lvoogdLUMC** [antigenomics/vdjdb-db#351]
[Voogd L et al. Mtb HLA-E-tetramer-sorted CD8+ T cells have a diverse TCR repertoire. iScience 2024](https://pubmed.ncbi.nlm.nih.gov/38439958/)

VDJ sequences of Mtb peptide specific CD8+ TCRs recognizing two HLA-E specific Mtb peptides that have been identified via tetramer sorting and sequencing.

Belongs to the manuscript: Mtb specific HLA-E restricted CD8+ T-cells have a highly diverse TCR repertoire (paper pending).

[VDJ and CDR3_VDJDB-database.xlsx](https://github.com/antigenomics/vdjdb-db/files/11788010/VDJ.and.CDR3_VDJDB-database.xlsx)

**Comment by lvoogdLUMC** [comment]
[VDJ and CDR3.xlsx](https://github.com/antigenomics/vdjdb-db/files/11555952/VDJ.and.CDR3.xlsx)

**Comment by lvoogdLUMC** [comment]
[VDJ and CDR3.xlsx](https://github.com/antigenomics/vdjdb-db/files/11565238/VDJ.and.CDR3.xlsx)

**Comment by mikessh** [comment]
Hello @lvoogdLUMC,
It seems that you have not attached the sequences. If you need assistance with formatting the data let me know

**Comment by lvoogdLUMC** [comment]
Hello,

That’s true. We are currently putting the data together as I forgot some sequences and I will upload these when I am back in the office on June 19.

All the best,
Linda

Op 1 jun. 2023 om 05:05 heeft Mikhail Shugay ***@***.***> het volgende geschreven:

﻿

Hello @lvoogdLUMC<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FlvoogdLUMC&data=05%7C01%7Cl.voogd%40lumc.nl%7C16e9d14f9666455cfb6608db624d151a%7Cc4048c4fdd544cbd80495457aacd2fb8%7C0%7C0%7C638211855433363641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mN9kETNR6I4w4ueN766XS5k1IHLJEYC7vv1LpEQAlGg%3D&reserved=0>,
It seems that you have not attached the sequences. If you need assistance with formatting the data let me know

**Comment by lvoogdLUMC** [comment]
> Hello @lvoogdLUMC, It seems that you have not attached the sequences. If you need assistance with formatting the data let me know


@mikessh I have attached an Excel file with the TCR sequences. Could you let me know if the format is ok? 

Best,
Linda Voogd

**Comment by mikessh** [comment]
Perhaps you can reformat it for this template https://raw.githubusercontent.com/antigenomics/vdjdb-db/master/template.xls ? It miss cell counts for each alpha/beta variant (those are not paired-chain, right?). And can you also please provide me the reference to the paper (doi or pubmed id).

**Comment by lvoogdLUMC** [comment]
@mikessh I have adjusted the file according to your template, thanks. These alpha/beta chains that are next to each other in the excel file are paired (per chunk.id). The paper is not yet published, which will hopefully happen soon. 
[VDJ and CDR3_submission.xlsx](https://github.com/antigenomics/vdjdb-db/files/11819818/VDJ.and.CDR3_submission.xlsx)

**Comment by mikessh** [comment]
@lvoogdLUMC hello, any news on the Pubmed ID of the paper?

**Comment by lvoogdLUMC** [comment]
@mikessh hello, no we are in the submission process and are waiting for reply of the editor. Publication might take a several weeks from now.

**Comment by lvoogdLUMC** [comment]
@mikessh Dear Mike, the paper is now published in iScience: 
Voogd et al., iScience 27,
https://doi.org/10.1016/j.isci.2024.109233

Could you please add this reference to the data file with TCR sequences?

Thank you
