### ISSUE TITLE
PMID:37749325

### ISSUE THREAD

**Issue by hayleymc** [antigenomics/vdjdb-db#354]
[van de Sandt CE et al. Newborn and child-like molecular signatures in older adults stem from TCR shifts across human lifespan. Nat Immunol. 2023 ](https://pubmed.ncbi.nlm.nih.gov/37749325/)

---

Hi all,

Could I please submit these records from the following paper which is not out yet:

Newborn and child-like molecular signatures in elderly stem from TCR shifts across the human lifespan. Nature Immunology, 2023.
Carolien E van de Sandt, Thi H O Nguyen, Nicholas A Gherardin, Jeremy Chase Crawford, Jerome Samir, Anastasia A Minervina, Mikhail V Pogorelyy, Simone Rizzetto, Christopher Szeto, Jasveen Kaur, Nicole Ranson, Sabrina Sonda, Alice Harper, Samuel J Redmond, Hayley A McQuilten, Tejas Menon, Sneha Sant, Xiaoxiao Jia, Kate Pedrina, Theo Karapanagiotidis, Natalie Cain, Suellen Nicholson, Zhenjun Chen, Ratana Lim, E Bridie Clemens, Auda Eltahla, Nicole L La Gruta, Jane Crowe, Martha Lappas, Jamie Rossjohn, Dale I Godfrey, Paul G Thomas, Stephanie Gras, Katie L Flanagan, Fabio Luciani and Katherine Kedzierska.

Thank you!!

[2023-08-09 VDJdb ex vivo A2M1 no phenotype_No Dash_no empty rows.xls](https://github.com/antigenomics/vdjdb-db/files/12298450/2023-08-09.VDJdb.ex.vivo.A2M1.no.phenotype_No.Dash_no.empty.rows.xls)
[2023-08-09 VDJdb Proliferation A2M1_No dash_NO EMPTY ROWS.xls](https://github.com/antigenomics/vdjdb-db/files/12298456/2023-08-09.VDJdb.Proliferation.A2M1_No.dash_NO.EMPTY.ROWS.xls)

**Comment by mikessh** [comment]
Added with minor fixes (removed non-coding CDR3aas), let me know what is the pubmed id when the paper is published

**Comment by hayleymc** [comment]
Will do - thank you!

**Comment by hayleymc** [comment]
Pubmed ID is 37749325
Thank you!
