### ISSUE TITLE
web gui down?

### ISSUE THREAD

**Issue by shreyii** [antigenomics/vdjdb-db#355]
hi team, 
I'm unable to access the web page of vdjdb on https://vdjdb.cdr3.net/.  
is it a global outage? kindly assist.

**Comment by mikessh** [comment]
Maintenance works are running since Monday. Unfortunately I cannot speed them up(

**Comment by shreyarajasekar** [comment]
Got it, thanks for the update. Any estimate of when it'll be up?

**Comment by mikessh** [comment]
Nope.. you can still download the whole version from https://github.com/antigenomics/vdjdb-db

**Comment by mikessh** [comment]
@shreyii up and running
