### ISSUE TITLE
PMID:38684663

### ISSUE THREAD

**Issue by TejasMenon** [antigenomics/vdjdb-db#361]
[Menon et al. CD8+ T-cell responses towards conserved influenza B virus epitopes across anatomical sites and age. Nat Commun 2024](https://pubmed.ncbi.nlm.nih.gov/38684663/)

---

Hi,

Can I please submit these records for the paper which has just been published under the pubmed ID: 38684663 ?

CD8+ T-cell responses towards conserved influenza B virus epitopes across anatomical sites and age.

Tejas Menon, Patricia T. Illing, Priyanka Chaurasia, Hayley A. McQuilten, Chloe Shepherd, Louise C. Rowntree, Jan Petersen, Dene R. Littler, Grace Khuu, Ziyi Huang, Lilith F. Allen, Steve Rockman, Jane Crowe, Katie L. Flanagan, Linda M. Wakim, Thi H. O. Nguyen, Nicole A. Mifsud, Jamie Rossjohn, Anthony W. Purcell, Carolien E van de Sandt and Katherine Kedzierska.
[Menon_TM_TCR data_VDJdb.xls](https://github.com/antigenomics/vdjdb-db/files/15159013/Menon_TM_TCR.data_VDJdb.xls)

Thanks!

**Comment by mikessh** [comment]
Hello, we're back from other projects and working on it
