### ISSUE TITLE
vdjmatch: WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by llrs** [antigenomics/vdjdb-db#378]
Thanks for releasing this software and creating the database (I hope to contribute to it once the data I have is published).

Apologies, my question is not about submitting new data but is not about the website but about vdjmatch. 
I am not sure if vdjmatch is maintained anymore but I see some warnings with vdjmatch at https://github.com/antigenomics/vdjmatch. 
As I can't open issues there I thought I would write it through here. 

Each time I run `java -jar ~/bin/vdjdb/vdjmatch-1.3.1.jar` I see:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:~/bin/vdjdb/vdjmatch-1.3.1.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

My java version is:

```
$ java --version
openjdk 11.0.23 2024-04-16
OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)
```

**Comment by mikessh** [comment]
This is a generic warning https://stackoverflow.com/questions/47935772/groovy-warning-an-illegal-reflective-access-operation-has-occurred
