### ISSUE TITLE
some bug during file-upload?

### ISSUE THREAD

**Issue by iziziz** [antigenomics/vdjdb-db#87]
[556-2.t2.txt](https://github.com/antigenomics/vdjdb-db/files/293868/556-2.t2.txt)
Failed to upload the cloneset (mitcr format). After pressing the button "Upload all" nothing is happening while green bar shows 'ok'...

**Comment by mikessh** [comment]
Issue moved to https://github.com/antigenomics/vdjdb-server/issues/10
