### ISSUE TITLE
horizontal scroll bar

### ISSUE THREAD

**Issue by iziziz** [antigenomics/vdjdb-db#88]
![screenshot from 2016-06-01 23 21 47](https://cloud.githubusercontent.com/assets/12457001/15724576/5e23e56a-2850-11e6-910e-d1ee974f4794.png)
smth is wrong with horizontal scroll bar in browsing section. There is no the bar )
Browser: Chromium Version 41.0.2272.76 Ubuntu 14.04 (64-bit)

**Comment by mikessh** [comment]
Issue moved to https://github.com/antigenomics/vdjdb-server/issues/11
